### ISSUE TITLE
[PE-D][Tester A] Person List in the main window

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-2/tp#138]
The person list in the main window does not expand when I make it full-screen after the view command.
![image.png](https://raw.githubusercontent.com/Clin-lyx/ped/main/files/8d3cb0aa-b7d8-4d40-949b-d2d60a078c9b.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Clin-lyx/ped#2

**Comment by jx124** [comment]
Could not replicate bug.

**Comment by LicongHuang** [comment]
Try on different operating system to see if bug persist

**Comment by garylow2001** [comment]
Could not replicate on Windows, Linux and Mac. Thus closing this issue.
