### ISSUE TITLE
[PE-D][Tester B] Output messages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-2/tp#162]
These are some suggestions to the team regarding output messages:

1. try to avoid showing null in the box as financial advisors probably wont know what that means and hence be confused. (eg. deletemeeting when there is no meeting, meeting field is not specified in addlead/addclient command)

2. when there is no clients/leads, maybe telling the user `there is no client/lead` would be better. This is because the product shows a lot of different kinds of list (sortmeeting, list, listclient, listlead, views) and some lists hide other contacts' information. Hence the user might be confused if there is really 0 client/lead or they are just hidden elsewhere.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LamJiuFong/ped#7

**Comment by jx124** [comment]
Point 2 is already implemented.

**Comment by jx124** [comment]
This is technically a ui enhancement, will revert the change.
