### ISSUE TITLE
[PE-D][Tester D] Cannot have people with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-2/tp#170]
All the other attributes differ

![Screenshot 2023-11-03 at 9.45.48 PM.png](https://raw.githubusercontent.com/RSXIX/ped/main/files/864b225b-9d36-40e3-acd5-1482ab5ea467.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: RSXIX/ped#6

**Comment by garylow2001** [comment]
Will clarify in updated UG
