### ISSUE TITLE
Project website is not working

### ISSUE THREAD

**Issue by tiif** [AY2324S1-CS2103T-F08-2/tp#2]
```
When set up correctly, your project website should be available via the URL https://ay2324s1-{team-id}.github.io/tp
e.g., https://ay2324s1-cs2103-w13-1.github.io/tp.
```
- This is not working yet, [source](https://nus-cs2103-ay2324s1.github.io/website/schedule/week6/project.html)

There is no issue running locally.

**Comment by jx124** [comment]
I believe the website is working now: https://ay2324s1-cs2103t-f08-2.github.io/tp/
